// Code generated by go generate; DO NOT EDIT.

package native

const macroContractSourceSHA256 = "6d60788f96647289e55485a6410b0a5d076725f2ec93eae31b131fb09be20572"

var macroActionContracts = map[byte]macroActionContract{
	0x10: {captureLength: 0x04}, // Buzzer
	0x11: {captureLength: 0x03}, // PwmSet
	0x12: {captureLength: 0x00}, // PwmAllOff
	0x14: {captureLength: 0x04}, // StatusRgb
	0x16: {captureLength: 0x05}, // AddressableLed
	0x17: {captureLength: 0xFF}, // StatusEffect
	0x20: {captureLength: 0x08}, // RadioTransmit
	0x30: {captureLength: 0x01}, // MenuAction
	0x31: {captureLength: 0x02}, // RelaySet
	0x32: {captureLength: 0x02}, // RelaySide
	0x33: {captureLength: 0x00}, // RelayAllOff
	0x37: {captureLength: 0x01}, // MenuSetPage
	0x38: {captureLength: 0xFF}, // DisplayText
	0x3D: {captureLength: 0x02}, // RemoteKeyGesture
}
