// Code generated by Tools/Build/generate-protocol-contract.mjs; DO NOT EDIT.
// Source: Project/ProtocolContract.json

package native

const (
	Magic            byte = 0xA5
	EnvelopeRevision byte = 1
)

const (
	MaxPayload       = 48
	RawFrameOverhead = 6
	MaxRawFrame      = MaxPayload + RawFrameOverhead
	MaxEncodedFrame  = MaxRawFrame + 2
)

const (
	OpHello             byte = 0x01
	OpGetStatus         byte = 0x02
	OpSetStream         byte = 0x03
	OpGetSettings       byte = 0x04
	OpSetSettings       byte = 0x05
	OpTemperatureList   byte = 0x06
	OpBuzzer            byte = 0x10
	OpPWMSet            byte = 0x11
	OpPWMAllOff         byte = 0x12
	OpStatusRGB         byte = 0x14
	OpPWMGet            byte = 0x15
	OpAddressableLED    byte = 0x16
	OpStatusEffect      byte = 0x17
	OpStatusProfileGet  byte = 0x18
	OpStatusProfileSet  byte = 0x19
	OpRFTx              byte = 0x20
	OpRFLearnStart      byte = 0x21
	OpRFLearnCancel     byte = 0x22
	OpRFLearnClear      byte = 0x23
	OpRFLearnList       byte = 0x24
	OpRFLearnRemove     byte = 0x25
	OpMenuAction        byte = 0x30
	OpRelaySet          byte = 0x31
	OpRelaySide         byte = 0x32
	OpRelayAllOff       byte = 0x33
	OpRelayTest         byte = 0x34
	OpReset             byte = 0x35
	OpI2CTransfer       byte = 0x36
	OpMenuSetPage       byte = 0x37
	OpDisplayText       byte = 0x38
	OpMacroStart        byte = 0x39
	OpMacroCancel       byte = 0x3A
	OpMacroStep         byte = 0x3B
	OpFrontPanelGet     byte = 0x3C
	OpRemoteKeyGesture  byte = 0x3D
	OpMenuList          byte = 0x3E
	OpRFLearnReplace    byte = 0x3F
	OpMenuLayoutGet     byte = 0x40
	OpMenuLayoutSet     byte = 0x41
	OpHostMenuDirectory byte = 0x42
	OpHostMenuContent   byte = 0x43
	OpHostMenuStateGet  byte = 0x44
	OpProgramState      byte = 0x45
	OpACK               byte = 0x80
	OpHelloResp         byte = 0x81
	OpError             byte = 0x82
	OpStatus            byte = 0x90
	OpSettings          byte = 0x91
	OpPWMValues         byte = 0x92
	OpI2CTransferResp   byte = 0x93
	OpRFEntries         byte = 0x94
	OpTemperatures      byte = 0x95
	OpFrontPanel        byte = 0x96
	OpMenuListResp      byte = 0x97
	OpMacroStatus       byte = 0x98
	OpMenuLayoutResp    byte = 0x99
	OpHostMenuRequest   byte = 0x9A
	OpHostMenuState     byte = 0x9B
	OpSegmentChanged    byte = 0x9C
	OpBuzzerChanged     byte = 0x9D
	OpStatusLEDChanged  byte = 0x9E
	OpStatusProfile     byte = 0x9F
	OpEvent             byte = 0xA0
)

const (
	ErrorNoError             byte = 0
	ErrorBadEnvelope         byte = 1
	ErrorUnsupported         byte = 2
	ErrorBadPayload          byte = 3
	ErrorHardwareUnavailable byte = 4
	ErrorBusy                byte = 5
	ErrorUnsafe              byte = 6
)
