package control

import (
	"context"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"pccontroller.local/controller/internal/appconfig"
	"pccontroller.local/controller/internal/native"
)

const (
	defaultMacroTimingToleranceUS uint32 = 2500
	macroStatusPollInterval              = 100 * time.Millisecond
	macroRequestTimeout                  = 2 * time.Second
)

// MacroState is the host-authoritative view shared by TUI, CLI, API, IPC, and
// bridge clients. Timing deltas are calculated solely from MCU timestamps.
type MacroState struct {
	Running              bool               `json:"running"`
	ID                   byte               `json:"id"`
	Name                 string             `json:"name"`
	Category             string             `json:"category,omitempty"`
	Color                string             `json:"color,omitempty"`
	Step                 int                `json:"step"`
	StepCount            int                `json:"step_count"`
	DurationUS           uint32             `json:"duration_us"`
	StartedAt            time.Time          `json:"started_at,omitempty"`
	FinishedAt           time.Time          `json:"finished_at,omitempty"`
	DeviceStartedAtUS    uint32             `json:"device_started_at_us,omitempty"`
	AcceptedBytes        uint16             `json:"accepted_bytes"`
	BufferFill           byte               `json:"buffer_fill"`
	Underruns            byte               `json:"underruns"`
	DispatchErrors       byte               `json:"dispatch_errors"`
	EvidenceSteps        int                `json:"evidence_steps"`
	TimingViolations     int                `json:"timing_violations"`
	LastTimingDeltaUS    int32              `json:"last_timing_delta_us"`
	MaximumTimingErrorUS uint32             `json:"maximum_timing_error_us"`
	TimingToleranceUS    uint32             `json:"timing_tolerance_us"`
	Faithful             bool               `json:"faithful"`
	Lifecycle            string             `json:"lifecycle,omitempty"`
	LastError            string             `json:"last_error,omitempty"`
	Device               native.MacroStatus `json:"device"`
}

type compiledMacroStep struct {
	dueUS        uint32
	opcode       byte
	recordLength int
	streamEnd    int
}

type compiledMacro struct {
	definition appconfig.Macro
	stream     []byte
	steps      []compiledMacroStep
	durationUS uint32
}

type MacroRunner struct {
	runtime          *Runtime
	library          func() []appconfig.Macro
	hostConfig       func() appconfig.Config
	updateHostConfig func(func(*appconfig.Config) error) error

	operationMu sync.Mutex
	mu          sync.RWMutex
	state       MacroState
	cancel      context.CancelFunc
	cancelKeep  bool
	done        chan struct{}

	recordMu      sync.RWMutex
	recording     MacroRecordingState
	recordMacro   appconfig.Macro
	recordBaseUS  uint32
	recordHasBase bool
	recordRelease func()
}

// MacroRecordingState describes a HOST-owned recording session. Each captured
// offset comes from the acknowledgement timestamp generated by the MCU.
type MacroRecordingState struct {
	Active    bool      `json:"active"`
	ID        byte      `json:"id"`
	Name      string    `json:"name"`
	Category  string    `json:"category,omitempty"`
	Color     string    `json:"color,omitempty"`
	Steps     int       `json:"steps"`
	StartedAt time.Time `json:"started_at,omitempty"`
	LastError string    `json:"last_error,omitempty"`
}

func NewMacroRunner(
	runtime *Runtime,
	library func() []appconfig.Macro,
	hostConfig func() appconfig.Config,
	updateHostConfig ...func(func(*appconfig.Config) error) error,
) *MacroRunner {
	if library == nil {
		library = func() []appconfig.Macro { return nil }
	}
	var updater func(func(*appconfig.Config) error) error
	if len(updateHostConfig) != 0 {
		updater = updateHostConfig[0]
	}
	return &MacroRunner{
		runtime: runtime, library: library, hostConfig: hostConfig,
		updateHostConfig: updater,
	}
}

func (runner *MacroRunner) List() []appconfig.Macro {
	source := runner.library()
	result := make([]appconfig.Macro, len(source))
	for index, macro := range source {
		result[index] = macro
		result[index].Steps = append([]appconfig.MacroStep(nil), macro.Steps...)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })
	return result
}

func (runner *MacroRunner) State() MacroState {
	runner.mu.RLock()
	defer runner.mu.RUnlock()
	return runner.state
}

func (runner *MacroRunner) RecordingState() MacroRecordingState {
	runner.recordMu.RLock()
	defer runner.recordMu.RUnlock()
	return runner.recording
}

// CreateDraft persists an empty, editable macro definition. Empty drafts are
// listable but intentionally cannot be played until they contain a step.
func (runner *MacroRunner) CreateDraft(id byte, name, category, color string) (appconfig.Macro, error) {
	if runner.updateHostConfig == nil {
		return appconfig.Macro{}, errors.New("macro persistence is unavailable")
	}
	macro := appconfig.Macro{
		ID: id, Name: strings.TrimSpace(name), Category: strings.TrimSpace(category),
		Color: normalizedMacroColor(color), TimingToleranceUS: defaultMacroTimingToleranceUS,
	}
	err := runner.updateHostConfig(func(config *appconfig.Config) error {
		for _, existing := range config.Macros {
			if existing.ID == id || strings.EqualFold(existing.Name, macro.Name) {
				return fmt.Errorf("macro ID %d or name %q already exists", id, macro.Name)
			}
		}
		config.Macros = append(config.Macros, macro)
		return nil
	})
	return macro, err
}

func (runner *MacroRunner) Delete(reference string) error {
	if runner.updateHostConfig == nil {
		return errors.New("macro persistence is unavailable")
	}
	macro, err := runner.find(reference)
	if err != nil {
		return err
	}
	state := runner.State()
	if state.Running && state.ID == macro.ID {
		return errors.New("cannot delete the macro currently playing")
	}
	return runner.updateHostConfig(func(config *appconfig.Config) error {
		for index, existing := range config.Macros {
			if existing.ID == macro.ID {
				config.Macros = append(config.Macros[:index], config.Macros[index+1:]...)
				return nil
			}
		}
		return fmt.Errorf("macro %q disappeared before it could be deleted", reference)
	})
}

func (runner *MacroRunner) StartRecording(name, category, color string) (MacroRecordingState, error) {
	if runner.updateHostConfig == nil {
		return MacroRecordingState{}, errors.New("macro persistence is unavailable")
	}
	name = strings.TrimSpace(name)
	if name == "" {
		return MacroRecordingState{}, errors.New("macro recording name is required")
	}
	color = normalizedMacroColor(color)
	if !validMacroColor(color) {
		return MacroRecordingState{}, fmt.Errorf("macro color %q is not red, blue, violet, green, or white", color)
	}
	used := make(map[byte]bool)
	for _, macro := range runner.List() {
		if strings.EqualFold(macro.Name, name) {
			return MacroRecordingState{}, fmt.Errorf("macro %q already exists", name)
		}
		used[macro.ID] = true
	}
	id := byte(0)
	for used[id] && id != 0xFF {
		id++
	}
	if used[id] {
		return MacroRecordingState{}, errors.New("all macro IDs are in use")
	}

	runner.recordMu.Lock()
	if runner.recording.Active {
		state := runner.recording
		runner.recordMu.Unlock()
		return state, fmt.Errorf("macro recording %q is already active", state.Name)
	}
	runner.recordMacro = appconfig.Macro{
		ID: id, Name: name, Category: strings.TrimSpace(category), Color: color,
		TimingToleranceUS: defaultMacroTimingToleranceUS,
	}
	runner.recordBaseUS = 0
	runner.recordHasBase = false
	runner.recording = MacroRecordingState{
		Active: true, ID: id, Name: name, Category: strings.TrimSpace(category),
		Color: color, StartedAt: time.Now(),
	}
	runner.recordRelease = runner.runtime.ObserveCommands(runner.captureCommand)
	state := runner.recording
	runner.recordMu.Unlock()
	runner.runtime.PublishStructuredEvent(Event{
		Kind: "macro.recording", Lifecycle: "started", State: "recording",
		Text: fmt.Sprintf("macro recording %d/%s started; MCU ACK deltas are authoritative", id, name),
	})
	return state, nil
}

func (runner *MacroRunner) StopRecording(save bool) (appconfig.Macro, error) {
	runner.recordMu.Lock()
	if !runner.recording.Active {
		runner.recordMu.Unlock()
		return appconfig.Macro{}, errors.New("no macro recording is active")
	}
	if runner.recordRelease != nil {
		runner.recordRelease()
		runner.recordRelease = nil
	}
	macro := runner.recordMacro
	runner.recording.Active = false
	runner.recording.Steps = len(macro.Steps)
	runner.recordMu.Unlock()

	if save {
		if len(macro.Steps) == 0 {
			return macro, errors.New("recording is empty; run at least one board command or discard it")
		}
		if err := runner.updateHostConfig(func(config *appconfig.Config) error {
			for _, existing := range config.Macros {
				if existing.ID == macro.ID || strings.EqualFold(existing.Name, macro.Name) {
					return fmt.Errorf("macro ID %d or name %q already exists", macro.ID, macro.Name)
				}
			}
			config.Macros = append(config.Macros, macro)
			return nil
		}); err != nil {
			return macro, err
		}
	}
	lifecycle := map[bool]string{true: "saved", false: "discarded"}[save]
	runner.runtime.PublishStructuredEvent(Event{
		Kind: "macro.recording", Lifecycle: lifecycle, State: lifecycle,
		Text: fmt.Sprintf("macro recording %d/%s %s with %d MCU-timed steps", macro.ID, macro.Name, lifecycle, len(macro.Steps)),
	})
	return macro, nil
}

func (runner *MacroRunner) captureCommand(evidence CommandEvidence) {
	if !evidence.Timed || !macroQueueableOpcode(evidence.Opcode) {
		return
	}
	step, ok := recordedMacroStep(evidence)
	if !ok {
		return
	}
	runner.recordMu.Lock()
	defer runner.recordMu.Unlock()
	if !runner.recording.Active {
		return
	}
	if !runner.recordHasBase {
		runner.recordBaseUS = evidence.DeviceMicros
		runner.recordHasBase = true
	}
	delta := evidence.DeviceMicros - runner.recordBaseUS
	if delta > 0x7FFFFFFF {
		runner.recording.LastError = "recording exceeded the MCU signed timing window"
		return
	}
	step.AtUS = delta
	runner.recordMacro.Steps = append(runner.recordMacro.Steps, step)
	runner.recording.Steps = len(runner.recordMacro.Steps)
}

// Start validates and buffers a macro before arming the MCU playback epoch.
// USB/network arrival timing therefore cannot shift already queued actions.
func (runner *MacroRunner) Start(ctx context.Context, reference string) (MacroState, error) {
	runner.operationMu.Lock()
	defer runner.operationMu.Unlock()

	macro, err := runner.find(reference)
	if err != nil {
		return MacroState{}, err
	}
	compiled, err := compileMacro(macro)
	if err != nil {
		return MacroState{}, err
	}
	snapshot := runner.runtime.Snapshot()
	if !snapshot.Connected {
		return MacroState{}, errors.New("device is not connected")
	}
	if snapshot.Hello.Capabilities&native.CapabilityTimedMacroQueue == 0 {
		return MacroState{}, errors.New("connected firmware does not advertise the MCU-timed macro queue")
	}
	if macroNeedsMotionPermission(macro) {
		if err := requireMotionAllowed(ctx, runner.runtime, runner.hostConfig); err != nil {
			return MacroState{}, err
		}
	}

	runner.mu.Lock()
	if runner.state.Running {
		state := runner.state
		runner.mu.Unlock()
		return state, fmt.Errorf("macro %d/%s is already running; cancel it first", state.ID, state.Name)
	}
	tolerance := macro.TimingToleranceUS
	if tolerance == 0 {
		tolerance = defaultMacroTimingToleranceUS
	}
	runner.state = MacroState{
		Running: true, ID: macro.ID, Name: macro.Name,
		Category: macro.Category, Color: normalizedMacroColor(macro.Color),
		StepCount: len(compiled.steps), DurationUS: compiled.durationUS,
		StartedAt: time.Now(), TimingToleranceUS: tolerance,
		Lifecycle: "buffering",
	}
	runner.mu.Unlock()

	lease, _, err := runner.runtime.AcquireProgramState(
		fmt.Sprintf("macro:%d", macro.ID),
		fmt.Sprintf("playing macro %s", macro.Name),
	)
	if err != nil {
		runner.failStart(macro, err)
		return runner.State(), err
	}
	begun := false
	fail := func(cause error) (MacroState, error) {
		if begun {
			if cleanupErr := runner.cancelBoard(false); cleanupErr != nil {
				cause = errors.Join(cause, fmt.Errorf("macro cleanup: %w", cleanupErr))
			}
		}
		lease.Release()
		runner.failStart(macro, cause)
		return runner.State(), cause
	}

	startPayload, err := native.MacroQueueStartPayload(
		macro.ID,
		uint16(len(compiled.steps)),
		macro.KeepOutputsOnCancel,
	)
	if err != nil {
		return fail(err)
	}
	if _, err = runner.request(ctx, native.OpMacroStart, startPayload, native.OpACK); err != nil {
		return fail(err)
	}
	begun = true
	afterID := runner.runtime.LatestEventID()
	sent, err := runner.appendBytes(ctx, compiled, 0, native.MacroQueueCapacity)
	if err != nil {
		return fail(err)
	}
	if err := runner.showMacroIdentity(ctx, compiled); err != nil {
		runner.runtime.PublishHostEvent("macro.display", "macro identity display unavailable: "+err.Error())
	}
	if _, err = runner.request(ctx, native.OpMacroStep, native.MacroQueueRunPayload(), native.OpACK); err != nil {
		return fail(err)
	}

	playContext, cancel := context.WithCancel(context.Background())
	done := make(chan struct{})
	runner.mu.Lock()
	runner.cancel = cancel
	runner.cancelKeep = false
	runner.done = done
	runner.state.Lifecycle = "playing"
	state := runner.state
	runner.mu.Unlock()
	runner.publishLifecycle("started", state, nil)
	go runner.play(playContext, done, compiled, sent, afterID, lease)
	return state, nil
}

// Cancel defaults to a safe stop: every relay and user PWM output is switched
// off. CancelWithPolicy(true) is the explicit opt-in that preserves outputs.
func (runner *MacroRunner) Cancel(ctx context.Context) error {
	return runner.CancelWithPolicy(ctx, false)
}

func (runner *MacroRunner) CancelWithPolicy(ctx context.Context, keepOutputs bool) error {
	runner.operationMu.Lock()
	defer runner.operationMu.Unlock()
	runner.mu.Lock()
	cancel := runner.cancel
	done := runner.done
	runner.cancelKeep = keepOutputs
	runner.mu.Unlock()
	if cancel != nil {
		cancel()
	}
	if done != nil {
		select {
		case <-done:
		case <-ctx.Done():
			return ctx.Err()
		}
		state := runner.State()
		if state.LastError != "" {
			return errors.New(state.LastError)
		}
		return nil
	}
	return runner.cancelBoard(keepOutputs)
}

func (runner *MacroRunner) find(reference string) (appconfig.Macro, error) {
	reference = strings.TrimSpace(reference)
	if reference == "" {
		return appconfig.Macro{}, fmt.Errorf("macro name or ID is required")
	}
	numericID, numericErr := strconv.ParseUint(reference, 0, 8)
	for _, macro := range runner.List() {
		if strings.EqualFold(macro.Name, reference) ||
			(numericErr == nil && uint64(macro.ID) == numericID) {
			return macro, nil
		}
	}
	return appconfig.Macro{}, fmt.Errorf("macro %q is not configured", reference)
}

func (runner *MacroRunner) play(
	ctx context.Context,
	done chan struct{},
	compiled compiledMacro,
	sent int,
	afterID uint64,
	lease *ProgramStateLease,
) {
	defer close(done)
	defer lease.Release()

	status, err := runner.queryBoard(ctx)
	if err == nil {
		runner.applyDeviceStatus(status)
	}
	lastQuery := time.Now()
	observed := 0
	watchdog := time.Duration(compiled.durationUS)*time.Microsecond + 10*time.Second
	if watchdog < 15*time.Second {
		watchdog = 15 * time.Second
	}
	deadline := time.Now().Add(watchdog)
	cancelled := false
	for err == nil {
		if ctx.Err() != nil {
			cancelled = true
			runner.mu.RLock()
			keep := runner.cancelKeep
			runner.mu.RUnlock()
			err = runner.cancelBoard(keep)
			if err == nil {
				status.State = native.MacroCancelled
			}
			break
		}
		if time.Now().After(deadline) {
			err = fmt.Errorf("macro playback exceeded its %s watchdog", watchdog)
			break
		}

		if status.Active() && sent < len(compiled.stream) && status.Free() != 0 {
			before := sent
			sent, err = runner.appendBytes(ctx, compiled, sent, int(status.Free()))
			if err != nil {
				break
			}
			status.Fill += byte(sent - before)
			status.AcceptedBytes = uint16(sent)
			status.AcceptedSteps = uint16(compiled.completeSteps(sent))
			runner.applyDeviceStatus(status)
		}

		if macroTerminal(status.State) {
			if observed >= len(compiled.steps) || status.State != native.MacroCompleted {
				break
			}
			// The final ACK precedes the completion event on the wire, but the
			// session pump can publish them on adjacent scheduler turns.
			deadline = minTime(deadline, time.Now().Add(150*time.Millisecond))
		}

		wait := macroStatusPollInterval - time.Since(lastQuery)
		if wait <= 0 {
			status, err = runner.queryBoard(ctx)
			lastQuery = time.Now()
			if err == nil {
				runner.applyDeviceStatus(status)
			}
			continue
		}
		waitContext, cancelWait := context.WithTimeout(ctx, wait)
		event, waitErr := runner.runtime.WaitEvent(waitContext, afterID, "")
		cancelWait()
		if waitErr != nil {
			if errors.Is(waitErr, context.DeadlineExceeded) {
				continue
			}
			if ctx.Err() != nil {
				continue
			}
			err = waitErr
			break
		}
		afterID = event.ID
		if event.Frame.Seq == native.MacroExecutionSequence {
			if observed < len(compiled.steps) {
				actualUS, timed := native.ResponseDeviceMicros(event.Frame)
				if timed {
					step := compiled.steps[observed]
					delta := int32(actualUS - (status.StartedAtUS + step.dueUS))
					runner.recordEvidence(observed, delta, event.Frame.Opcode == native.OpACK)
					if int(status.Fill) >= step.recordLength {
						status.Fill -= byte(step.recordLength)
					} else {
						status.Fill = 0
					}
					observed++
				}
				status.ExecutedSteps = uint16(observed + 1)
				runner.applyDeviceStatus(status)
			}
			continue
		}
		if event.Frame.Opcode == native.OpEvent {
			deviceEvent, parseErr := native.ParseDeviceEvent(event.Frame.Payload)
			if parseErr == nil && deviceEvent.Macro != nil &&
				deviceEvent.Macro.ID == compiled.definition.ID &&
				deviceEvent.Macro.State != native.MacroBuffering {
				status = *deviceEvent.Macro
				runner.applyDeviceStatus(status)
			}
		}
	}
	if ctx.Err() != nil && !cancelled {
		cancelled = true
		runner.mu.RLock()
		keep := runner.cancelKeep
		runner.mu.RUnlock()
		cancelErr := runner.cancelBoard(keep)
		if cancelErr == nil {
			status.State = native.MacroCancelled
			err = nil
		} else {
			err = errors.Join(ctx.Err(), cancelErr)
		}
	}

	if err != nil && !cancelled {
		if cleanupErr := runner.cancelBoard(false); cleanupErr != nil {
			err = errors.Join(err, fmt.Errorf("macro safe-stop cleanup: %w", cleanupErr))
		}
	}
	runner.finishPlayback(done, compiled.definition, status, observed, cancelled, err)
}

func (runner *MacroRunner) appendBytes(
	ctx context.Context,
	compiled compiledMacro,
	offset int,
	available int,
) (int, error) {
	for offset < len(compiled.stream) && available > 0 {
		length := len(compiled.stream) - offset
		if length > native.MacroMaximumFragment {
			length = native.MacroMaximumFragment
		}
		if length > available {
			length = available
		}
		payload, err := native.MacroQueueAppendPayload(
			uint16(offset),
			uint16(compiled.completeSteps(offset+length)),
			compiled.stream[offset:offset+length],
		)
		if err != nil {
			return offset, err
		}
		if _, err := runner.request(ctx, native.OpMacroStep, payload, native.OpACK); err != nil {
			return offset, err
		}
		offset += length
		available -= length
	}
	return offset, nil
}

func (runner *MacroRunner) queryBoard(ctx context.Context) (native.MacroStatus, error) {
	frame, err := runner.request(
		ctx,
		native.OpMacroStep,
		native.MacroQueueQueryPayload(),
		native.OpMacroStatus,
	)
	if err != nil {
		return native.MacroStatus{}, err
	}
	return native.ParseMacroStatus(frame.Payload)
}

func (runner *MacroRunner) request(
	ctx context.Context,
	opcode byte,
	payload []byte,
	expected byte,
) (native.Frame, error) {
	requestContext, cancel := context.WithTimeout(ctx, macroRequestTimeout)
	defer cancel()
	return runner.runtime.Request(requestContext, opcode, payload, expected)
}

func (runner *MacroRunner) cancelBoard(keepOutputs bool) error {
	ctx, cancel := context.WithTimeout(context.Background(), macroRequestTimeout)
	defer cancel()
	_, err := runner.runtime.Request(
		ctx,
		native.OpMacroCancel,
		native.MacroQueueCancelPayload(keepOutputs),
		native.OpACK,
	)
	return err
}

func (runner *MacroRunner) showMacroIdentity(ctx context.Context, compiled compiledMacro) error {
	macro := compiled.definition
	label := strings.TrimSpace(macro.Label)
	if label == "" {
		label = macro.Name
	}
	if len(label) > 4 {
		label = label[:4]
	}
	durationMS := uint32(compiled.durationUS/1000) + 1500
	if durationMS > 65535 {
		durationMS = 65535
	}
	if label != "" {
		payload, err := native.DisplayTextPayload(native.DisplaySegments, uint16(durationMS), label)
		if err != nil {
			return err
		}
		if _, err := runner.request(ctx, native.OpDisplayText, payload, native.OpACK); err != nil {
			return err
		}
	}
	if macro.LCDMessage != "" {
		payload, err := native.DisplayTextPayload(native.DisplayLCD, uint16(durationMS), macro.LCDMessage)
		if err != nil {
			return err
		}
		if _, err := runner.request(ctx, native.OpDisplayText, payload, native.OpACK); err != nil {
			return err
		}
	}
	return nil
}

func (runner *MacroRunner) applyDeviceStatus(status native.MacroStatus) {
	runner.mu.Lock()
	runner.state.Device = status
	runner.state.DeviceStartedAtUS = status.StartedAtUS
	runner.state.AcceptedBytes = status.AcceptedBytes
	runner.state.BufferFill = status.Fill
	runner.state.Underruns = status.Underruns
	runner.state.DispatchErrors = status.DispatchErrors
	runner.mu.Unlock()
}

func (runner *MacroRunner) recordEvidence(index int, delta int32, succeeded bool) {
	runner.mu.Lock()
	runner.state.Step = index + 1
	runner.state.EvidenceSteps = index + 1
	runner.state.LastTimingDeltaUS = delta
	absolute := uint32(delta)
	if delta < 0 {
		absolute = uint32(-int64(delta))
	}
	if absolute > runner.state.MaximumTimingErrorUS {
		runner.state.MaximumTimingErrorUS = absolute
	}
	if absolute > runner.state.TimingToleranceUS {
		runner.state.TimingViolations++
	}
	state := runner.state
	runner.mu.Unlock()
	runner.runtime.PublishStructuredEvent(Event{
		Kind: "macro.step", Lifecycle: "executed", State: map[bool]string{true: "acknowledged", false: "rejected"}[succeeded],
		Text: fmt.Sprintf("macro %d/%s step %d/%d delta=%dus", state.ID, state.Name, index+1, state.StepCount, delta),
		Metadata: map[string]string{
			"macro_id": strconv.Itoa(int(state.ID)), "macro_name": state.Name,
			"step": strconv.Itoa(index + 1), "steps": strconv.Itoa(state.StepCount),
			"mcu_delta_us": strconv.FormatInt(int64(delta), 10),
		},
	})
}

func (runner *MacroRunner) finishPlayback(
	done chan struct{},
	macro appconfig.Macro,
	status native.MacroStatus,
	observed int,
	cancelled bool,
	err error,
) {
	runner.mu.Lock()
	if runner.done != done {
		runner.mu.Unlock()
		return
	}
	runner.state.Running = false
	runner.state.FinishedAt = time.Now()
	runner.state.Device = status
	runner.state.Underruns = status.Underruns
	runner.state.DispatchErrors = status.DispatchErrors
	runner.state.BufferFill = status.Fill
	runner.state.AcceptedBytes = status.AcceptedBytes
	runner.state.Faithful = err == nil && !cancelled &&
		status.State == native.MacroCompleted &&
		status.Underruns == 0 && status.DispatchErrors == 0 &&
		observed == len(macro.Steps) && runner.state.TimingViolations == 0
	switch {
	case err != nil:
		runner.state.Lifecycle = "failed"
		runner.state.LastError = err.Error()
	case cancelled || status.State == native.MacroCancelled:
		runner.state.Lifecycle = "cancelled"
		runner.state.LastError = ""
	case status.State != native.MacroCompleted:
		err = fmt.Errorf("macro ended in device state %d", status.State)
		runner.state.Lifecycle = "failed"
		runner.state.LastError = err.Error()
	default:
		runner.state.Lifecycle = "completed"
		runner.state.LastError = ""
	}
	runner.cancel = nil
	runner.done = nil
	state := runner.state
	runner.mu.Unlock()
	runner.publishLifecycle(state.Lifecycle, state, err)
}

func (runner *MacroRunner) failStart(macro appconfig.Macro, err error) {
	runner.mu.Lock()
	runner.state.Running = false
	runner.state.FinishedAt = time.Now()
	runner.state.Lifecycle = "failed"
	runner.state.LastError = err.Error()
	state := runner.state
	runner.mu.Unlock()
	runner.publishLifecycle("failed", state, err)
}

func (runner *MacroRunner) publishLifecycle(lifecycle string, state MacroState, err error) {
	text := fmt.Sprintf("macro %d/%s %s", state.ID, state.Name, lifecycle)
	if err != nil {
		text += ": " + err.Error()
	}
	runner.runtime.PublishStructuredEvent(Event{
		Kind: "macro", Lifecycle: lifecycle, State: lifecycle, Text: text,
		Metadata: map[string]string{
			"macro_id": strconv.Itoa(int(state.ID)), "macro_name": state.Name,
			"category": state.Category, "color": state.Color,
			"step": strconv.Itoa(state.Step), "steps": strconv.Itoa(state.StepCount),
			"faithful":        strconv.FormatBool(state.Faithful),
			"timing_error_us": strconv.FormatUint(uint64(state.MaximumTimingErrorUS), 10),
			"underruns":       strconv.Itoa(int(state.Underruns)),
			"dispatch_errors": strconv.Itoa(int(state.DispatchErrors)),
		},
	})
}

func compileMacro(macro appconfig.Macro) (compiledMacro, error) {
	if len(macro.Steps) == 0 || len(macro.Steps) > 65535 {
		return compiledMacro{}, fmt.Errorf("macro %d/%s must contain 1..65535 steps", macro.ID, macro.Name)
	}
	result := compiledMacro{definition: macro, steps: make([]compiledMacroStep, 0, len(macro.Steps))}
	var previous uint32
	for index, step := range macro.Steps {
		dueUS, err := macroStepDueUS(step)
		if err != nil {
			return compiledMacro{}, fmt.Errorf("macro %d/%s step %d: %w", macro.ID, macro.Name, index+1, err)
		}
		if index != 0 && dueUS < previous {
			return compiledMacro{}, fmt.Errorf("macro %d/%s step %d timing is not ordered", macro.ID, macro.Name, index+1)
		}
		opcode, payload, err := compileMacroCommand(step)
		if err != nil {
			return compiledMacro{}, fmt.Errorf("macro %d/%s step %d: %w", macro.ID, macro.Name, index+1, err)
		}
		record, err := native.EncodeMacroRecord(dueUS, opcode, payload)
		if err != nil {
			return compiledMacro{}, fmt.Errorf("macro %d/%s step %d: %w", macro.ID, macro.Name, index+1, err)
		}
		if len(result.stream)+len(record) > 65535 {
			return compiledMacro{}, fmt.Errorf("macro %d/%s encoded stream exceeds 65535 bytes", macro.ID, macro.Name)
		}
		result.stream = append(result.stream, record...)
		result.steps = append(result.steps, compiledMacroStep{
			dueUS: dueUS, opcode: opcode, recordLength: len(record), streamEnd: len(result.stream),
		})
		previous = dueUS
	}
	result.durationUS = previous
	return result, nil
}

func (compiled compiledMacro) completeSteps(offset int) int {
	return sort.Search(len(compiled.steps), func(index int) bool {
		return compiled.steps[index].streamEnd > offset
	})
}

func macroStepDueUS(step appconfig.MacroStep) (uint32, error) {
	due := step.AtUS
	if due > 0x7FFFFFFF {
		return 0, errors.New("timing exceeds 2147483647 us")
	}
	return due, nil
}

func compileMacroCommand(step appconfig.MacroStep) (byte, []byte, error) {
	switch strings.ToLower(strings.TrimSpace(step.Kind)) {
	case "relay":
		payload, err := native.RelayPayload(step.Target, step.Value != 0)
		if step.Value > 1 {
			err = fmt.Errorf("relay value %d is outside 0..1", step.Value)
		}
		return native.OpRelaySet, payload, err
	case "motion", "side":
		payload, err := native.RelaySidePayload(step.Target, byte(step.Value))
		return native.OpRelaySide, payload, err
	case "pwm", "mosfet":
		payload, err := native.PWMSetPayload(step.Target, step.Value)
		return native.OpPWMSet, payload, err
	case "relays-off":
		return native.OpRelayAllOff, nil, nil
	case "pwm-off":
		return native.OpPWMAllOff, nil, nil
	case "buzzer", "tone":
		frequency := step.FrequencyHz
		if frequency == 0 {
			frequency = step.Value
		}
		if step.DurationMS == 0 || (frequency != 0 && (frequency < 20 || frequency > 20000)) {
			return 0, nil, errors.New("buzzer requires duration_ms and frequency 0 or 20..20000 Hz")
		}
		return native.OpBuzzer, native.BuzzerPayload(frequency, step.DurationMS), nil
	case "display", "message":
		target := native.DisplayBoth
		switch strings.ToLower(strings.TrimSpace(step.Destination)) {
		case "segments", "segment":
			target = native.DisplaySegments
		case "lcd":
			target = native.DisplayLCD
		case "", "both":
		default:
			return 0, nil, fmt.Errorf("display destination %q is unknown", step.Destination)
		}
		payload, err := native.DisplayTextPayload(target, step.DurationMS, step.Text)
		return native.OpDisplayText, payload, err
	case "rf", "radio":
		payload, err := native.RFTxPayload(step.Code, step.Bits, step.Protocol, step.PulseUS)
		return native.OpRFTx, payload, err
	case "rgb", "status-led":
		return native.OpStatusRGB, native.StatusRGBPayload(step.Red, step.Green, step.Blue, step.Brightness), nil
	case "addressable", "ws2812":
		payload, err := native.AddressableLEDPayload(step.Target, step.Red, step.Green, step.Blue, step.Brightness)
		return native.OpAddressableLED, payload, err
	case "menu":
		return native.OpMenuSetPage, []byte{step.Target}, nil
	case "menu-action":
		if step.Target > native.MenuIncrease {
			return 0, nil, fmt.Errorf("menu action %d is outside 0..3", step.Target)
		}
		return native.OpMenuAction, []byte{step.Target}, nil
	case "raw", "opcode":
		if !macroQueueableOpcode(step.Opcode) {
			return 0, nil, fmt.Errorf("opcode 0x%02X is not a queueable acknowledged command", step.Opcode)
		}
		payload, err := decodeMacroHex(step.PayloadHex)
		return step.Opcode, payload, err
	default:
		return 0, nil, fmt.Errorf("unknown macro step kind %q", step.Kind)
	}
}

func macroQueueableOpcode(opcode byte) bool {
	switch opcode {
	case native.OpSetStream, native.OpSetSettings,
		native.OpBuzzer, native.OpPWMSet, native.OpPWMAllOff,
		native.OpStatusRGB, native.OpAddressableLED, native.OpRFTx,
		native.OpRFLearnStart, native.OpRFLearnCancel, native.OpRFLearnClear,
		native.OpRFLearnRemove, native.OpRFLearnReplace,
		native.OpMenuAction, native.OpRelaySet, native.OpRelaySide,
		native.OpRelayAllOff, native.OpRelayTest, native.OpMenuSetPage,
		native.OpDisplayText, native.OpRemoteKeyGesture:
		return true
	default:
		return false
	}
}

func decodeMacroHex(value string) ([]byte, error) {
	value = strings.NewReplacer(" ", "", "\t", "", ":", "", "-", "").Replace(strings.TrimSpace(value))
	payload, err := hex.DecodeString(value)
	if err != nil {
		return nil, fmt.Errorf("decode payload_hex: %w", err)
	}
	if len(payload) > native.MaxPayload {
		return nil, native.ErrPayloadTooLong
	}
	return payload, nil
}

func recordedMacroStep(evidence CommandEvidence) (appconfig.MacroStep, bool) {
	payload := evidence.Payload
	step := appconfig.MacroStep{}
	switch evidence.Opcode {
	case native.OpRelaySet:
		if len(payload) != 2 {
			return step, false
		}
		step.Kind, step.Target, step.Value = "relay", payload[0], uint16(payload[1])
	case native.OpRelaySide:
		if len(payload) != 2 {
			return step, false
		}
		step.Kind, step.Target, step.Value = "motion", payload[0], uint16(payload[1])
	case native.OpRelayAllOff:
		step.Kind = "relays-off"
	case native.OpPWMSet:
		if len(payload) != 3 {
			return step, false
		}
		step.Kind, step.Target = "pwm", payload[0]
		step.Value = binary.LittleEndian.Uint16(payload[1:3])
	case native.OpPWMAllOff:
		step.Kind = "pwm-off"
	case native.OpBuzzer:
		if len(payload) != 4 {
			return step, false
		}
		step.Kind = "buzzer"
		step.FrequencyHz = binary.LittleEndian.Uint16(payload[0:2])
		step.DurationMS = binary.LittleEndian.Uint16(payload[2:4])
	case native.OpDisplayText:
		if len(payload) < 4 || int(payload[3])+4 != len(payload) || payload[0] > native.DisplayBoth {
			return step, false
		}
		step.Kind = "display"
		step.DurationMS = binary.LittleEndian.Uint16(payload[1:3])
		step.Text = string(payload[4:])
		step.Destination = map[byte]string{
			native.DisplaySegments: "segments", native.DisplayLCD: "lcd", native.DisplayBoth: "both",
		}[payload[0]]
	case native.OpRFTx:
		if len(payload) != 8 {
			return step, false
		}
		step.Kind = "rf"
		step.Code = binary.LittleEndian.Uint32(payload[0:4])
		step.Bits, step.Protocol = payload[4], payload[5]
		step.PulseUS = binary.LittleEndian.Uint16(payload[6:8])
	case native.OpStatusRGB:
		if len(payload) != 4 {
			return step, false
		}
		step.Kind = "status-led"
		step.Red, step.Green, step.Blue, step.Brightness = payload[0], payload[1], payload[2], payload[3]
	case native.OpAddressableLED:
		if len(payload) != 5 {
			return step, false
		}
		step.Kind, step.Target = "addressable", payload[0]
		step.Red, step.Green, step.Blue, step.Brightness = payload[1], payload[2], payload[3], payload[4]
	case native.OpMenuSetPage:
		if len(payload) != 1 {
			return step, false
		}
		step.Kind, step.Target = "menu", payload[0]
	case native.OpMenuAction:
		if len(payload) != 1 {
			return step, false
		}
		step.Kind, step.Target = "menu-action", payload[0]
	default:
		step.Kind = "raw"
		step.Opcode = evidence.Opcode
		step.PayloadHex = strings.ToUpper(hex.EncodeToString(payload))
	}
	return step, true
}

func macroNeedsMotionPermission(macro appconfig.Macro) bool {
	for _, step := range macro.Steps {
		kind := strings.ToLower(strings.TrimSpace(step.Kind))
		if (kind == "relay" && step.Target < 4 && step.Value != 0) ||
			((kind == "motion" || kind == "side") && step.Value != 0) {
			return true
		}
	}
	return false
}

func normalizedMacroColor(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	if value == "purple" {
		return "violet"
	}
	return value
}

func validMacroColor(value string) bool {
	switch normalizedMacroColor(value) {
	case "", "red", "blue", "violet", "green", "white":
		return true
	default:
		return false
	}
}

func macroTerminal(state byte) bool {
	return state == native.MacroCancelled || state == native.MacroCompleted || state == native.MacroFailed
}

func minTime(first, second time.Time) time.Time {
	if first.Before(second) {
		return first
	}
	return second
}
