#include <stdio.h>
#include <string.h>

// This header is generated by the actual `go build -buildmode=c-shared`
// target. Include it in every smoke consumer so an ABI signature drift fails
// at compile time instead of being hidden by a handwritten declaration.
#include "pccontroller.h"

#if defined(_WIN32)
#include <windows.h>
#define PCCONTROLLER_LIBRARY "pccontroller.dll"
#else
#include <dlfcn.h>
#if defined(__APPLE__)
#define PCCONTROLLER_LIBRARY "pccontroller.dylib"
#else
#define PCCONTROLLER_LIBRARY "pccontroller.so"
#endif
#endif

// The supported CMake compilers are GCC/Clang-family compilers. Derive the
// loader types directly from the generated declarations rather than repeating
// handwritten function prototypes in this consumer.
#if defined(__GNUC__) || defined(__clang__)
typedef __typeof__(&PCControllerInvoke) pccontroller_invoke_fn;
typedef __typeof__(&PCControllerFree) pccontroller_free_fn;
#else
#error "The PCController C ABI smoke requires a compiler with __typeof__ support"
#endif

int main(void) {
  // Load dynamically so this stays an external C ABI consumer rather than a
  // second link-time owner of Go's process-lifetime runtime.
#if defined(_WIN32)
  HMODULE library = LoadLibraryA(PCCONTROLLER_LIBRARY);
  if (library == NULL) {
    fprintf(stderr, "LoadLibrary failed: %lu\n", GetLastError());
    return 1;
  }

  FARPROC invoke_symbol = GetProcAddress(library, "PCControllerInvoke");
  FARPROC release_symbol = GetProcAddress(library, "PCControllerFree");
  _Static_assert(sizeof(pccontroller_invoke_fn) == sizeof(invoke_symbol),
                 "Windows function pointers must have a uniform representation");
  _Static_assert(sizeof(pccontroller_free_fn) == sizeof(release_symbol),
                 "Windows function pointers must have a uniform representation");
  pccontroller_invoke_fn invoke;
  pccontroller_free_fn release;
  memcpy(&invoke, &invoke_symbol, sizeof(invoke));
  memcpy(&release, &release_symbol, sizeof(release));
#else
  void *library = dlopen("./" PCCONTROLLER_LIBRARY, RTLD_NOW | RTLD_LOCAL);
  if (library == NULL) {
    fprintf(stderr, "dlopen failed: %s\n", dlerror());
    return 1;
  }
  void *invoke_symbol = dlsym(library, "PCControllerInvoke");
  void *release_symbol = dlsym(library, "PCControllerFree");
  _Static_assert(sizeof(pccontroller_invoke_fn) == sizeof(invoke_symbol),
                 "POSIX function pointers must have a uniform representation");
  _Static_assert(sizeof(pccontroller_free_fn) == sizeof(release_symbol),
                 "POSIX function pointers must have a uniform representation");
  pccontroller_invoke_fn invoke;
  pccontroller_free_fn release;
  memcpy(&invoke, &invoke_symbol, sizeof(invoke));
  memcpy(&release, &release_symbol, sizeof(release));
#endif
  if (invoke == NULL || release == NULL) {
    fprintf(stderr, "required C ABI exports are missing\n");
    return 2;
  }

  char request[] = "{\"operation\":\"ports\"}";
  char *response = invoke(request);
  if (response == NULL) {
    fprintf(stderr, "PCControllerInvoke returned NULL\n");
    return 3;
  }
  puts(response);
  const int valid = strstr(response, "\"ok\":true") != NULL;
  release(response);
  if (!valid) {
    return 4;
  }

  char create_host[] =
      "{\"operation\":\"host_create\",\"host_options\":{"
      "\"config_path\":\"pccontroller-smoke-config.json\","
      "\"app_id\":\"pccontroller.c-smoke\","
      "\"controller_options\":{},"
      "\"disable_auto_connect\":true,"
      "\"disable_native\":true}}";
  response = invoke(create_host);
  if (response == NULL || strstr(response, "\"ok\":true") == NULL) {
    return 5;
  }
  char *handle_field = strstr(response, "\"handle\":");
  if (handle_field == NULL) {
    return 6;
  }
  const unsigned long long handle = strtoull(handle_field + 9, NULL, 10);
  release(response);

  char lifecycle_request[512];
  snprintf(lifecycle_request, sizeof(lifecycle_request),
           "{\"operation\":\"host_start\",\"handle\":%llu}", handle);
  response = invoke(lifecycle_request);
  if (response == NULL || strstr(response, "\"ok\":true") == NULL) {
    return 7;
  }
  release(response);

  snprintf(lifecycle_request, sizeof(lifecycle_request),
           "{\"operation\":\"host_call\",\"handle\":%llu,"
           "\"method\":\"controller.ping\",\"params\":{}}",
           handle);
  response = invoke(lifecycle_request);
  char *result_field =
      response == NULL ? NULL : strstr(response, "\"result\":{");
  if (response == NULL || result_field == NULL ||
      strstr(result_field, "\"ok\":true") == NULL) {
    return 8;
  }
  release(response);

  snprintf(lifecycle_request, sizeof(lifecycle_request),
           "{\"operation\":\"host_destroy\",\"handle\":%llu}", handle);
  response = invoke(lifecycle_request);
  if (response == NULL || strstr(response, "\"destroyed\":true") == NULL) {
    return 9;
  }
  release(response);
  remove("pccontroller-smoke-config.json");

  // A Go c-shared runtime is process-lifetime state. Do not FreeLibrary here;
  // normal consumers should unload it only as part of process shutdown.
  return 0;
}
