// Command genmacrocontract compiles the canonical C++ protocol/action tables
// into the Go host lookup. The generated source is intentionally numeric so
// naming style differences cannot become a second handwritten mapping.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var (
	enumRow   = regexp.MustCompile(`(?m)^\s*([A-Za-z][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+|[0-9]+)\s*,`)
	actionRow = regexp.MustCompile(`(?m)^\s*PCCONTROLLER_MACRO_ACTION\(\s*([A-Za-z][A-Za-z0-9_]*)\s*,\s*(0x[0-9A-Fa-f]+|[0-9]+)\s*\)`)
)

type action struct {
	name          string
	opcode        uint8
	captureLength uint8
}

func main() {
	protocolPath := flag.String("protocol", "", "path to Project/ProtocolContract.h")
	actionsPath := flag.String("actions", "", "path to canonical MacroActions data")
	outputPath := flag.String("output", "", "generated Go output")
	flag.Parse()
	if *protocolPath == "" || *actionsPath == "" || *outputPath == "" {
		fatalf("-protocol, -actions, and -output are required")
	}
	protocol, err := os.ReadFile(*protocolPath)
	if err != nil {
		fatalf("read protocol: %v", err)
	}
	actionsSource, err := os.ReadFile(*actionsPath)
	if err != nil {
		fatalf("read actions: %v", err)
	}
	opcodes, err := parseOpcodes(protocol)
	if err != nil {
		fatalf("parse protocol: %v", err)
	}
	actions, err := parseActions(actionsSource, opcodes)
	if err != nil {
		fatalf("parse actions: %v", err)
	}
	hash := sha256.New()
	_, _ = hash.Write(protocol)
	_, _ = hash.Write([]byte{0})
	_, _ = hash.Write(actionsSource)
	sourceHash := fmt.Sprintf("%x", hash.Sum(nil))

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&generated)
	fmt.Fprintln(&generated, "package native")
	fmt.Fprintln(&generated)
	fmt.Fprintf(&generated, "const macroContractSourceSHA256 = %q\n\n", sourceHash)
	fmt.Fprintln(&generated, "var macroActionContracts = map[byte]macroActionContract{")
	for _, row := range actions {
		fmt.Fprintf(
			&generated,
			"\t0x%02X: {captureLength: 0x%02X}, // %s\n",
			row.opcode,
			row.captureLength,
			row.name,
		)
	}
	fmt.Fprintln(&generated, "}")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format generated source: %v\n%s", err, generated.String())
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func parseOpcodes(source []byte) (map[string]uint8, error) {
	result := make(map[string]uint8)
	for _, match := range enumRow.FindAllSubmatch(source, -1) {
		value, err := strconv.ParseUint(string(match[2]), 0, 8)
		if err != nil {
			return nil, fmt.Errorf("%s value %q: %w", match[1], match[2], err)
		}
		name := string(match[1])
		if previous, exists := result[name]; exists && previous != uint8(value) {
			return nil, fmt.Errorf("duplicate opcode name %s", name)
		}
		result[name] = uint8(value)
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("no opcode rows found")
	}
	return result, nil
}

func parseActions(source []byte, opcodes map[string]uint8) ([]action, error) {
	var result []action
	seenOpcode := make(map[uint8]string)
	for _, match := range actionRow.FindAllSubmatch(source, -1) {
		name := string(match[1])
		opcode, exists := opcodes[name]
		if !exists {
			return nil, fmt.Errorf("action %s has no canonical opcode", name)
		}
		value, err := strconv.ParseUint(string(match[2]), 0, 8)
		if err != nil {
			return nil, fmt.Errorf("%s capture length %q: %w", name, match[2], err)
		}
		if previous, exists := seenOpcode[opcode]; exists {
			return nil, fmt.Errorf("actions %s and %s share opcode 0x%02X", previous, name, opcode)
		}
		seenOpcode[opcode] = name
		result = append(result, action{name: name, opcode: opcode, captureLength: uint8(value)})
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("no PCCONTROLLER_MACRO_ACTION rows found in %s", strings.TrimSpace(string(source)))
	}
	sort.Slice(result, func(i, j int) bool { return result[i].opcode < result[j].opcode })
	return result, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genmacrocontract: "+format+"\n", args...)
	os.Exit(1)
}
