// Command genmacrocontract compiles the canonical C++ protocol/action tables
// into the Go host lookup. The generated source is intentionally numeric so
// naming style differences cannot become a second handwritten mapping.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var (
	enumRow   = regexp.MustCompile(`(?m)^\s*([A-Za-z][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+|[0-9]+)\s*,`)
	actionRow = regexp.MustCompile(`(?m)^\s*PCCONTROLLER_MACRO_ACTION\(\s*([A-Za-z][A-Za-z0-9_]*)\s*,\s*(0x[0-9A-Fa-f]+|[0-9]+)\s*\)`)
	enumBlock = regexp.MustCompile(`(?s)enum\s+([A-Za-z][A-Za-z0-9_]*)\s*:\s*uint8_t\s*\{(.*?)\};`)
	valueRow  = regexp.MustCompile(`(?m)^\s*([A-Za-z][A-Za-z0-9_]*)\s*=\s*([^,]+),`)
	shiftExpr = regexp.MustCompile(`^1U?\s*<<\s*([0-7])$`)
)

type action struct {
	name          string
	opcode        uint8
	captureLength uint8
}

type namedValue struct {
	name  string
	value uint8
}

func main() {
	protocolPath := flag.String("protocol", "", "path to Project/ProtocolContract.h")
	actionsPath := flag.String("actions", "", "path to canonical MacroActions data")
	outputPath := flag.String("output", "", "generated Go output")
	flag.Parse()
	if *protocolPath == "" || *actionsPath == "" || *outputPath == "" {
		fatalf("-protocol, -actions, and -output are required")
	}
	protocol, err := os.ReadFile(*protocolPath)
	if err != nil {
		fatalf("read protocol: %v", err)
	}
	actionsSource, err := os.ReadFile(*actionsPath)
	if err != nil {
		fatalf("read actions: %v", err)
	}
	opcodes, err := parseOpcodes(protocol)
	if err != nil {
		fatalf("parse protocol: %v", err)
	}
	actions, err := parseActions(actionsSource, opcodes)
	if err != nil {
		fatalf("parse actions: %v", err)
	}
	profiles, err := parseUint8Enum(protocol, "FeatureProfile")
	if err != nil {
		fatalf("parse feature profiles: %v", err)
	}
	features, err := parseUint8Enum(protocol, "BuildFeatureFlag")
	if err != nil {
		fatalf("parse build feature flags: %v", err)
	}
	hash := sha256.New()
	_, _ = hash.Write(protocol)
	_, _ = hash.Write([]byte{0})
	_, _ = hash.Write(actionsSource)
	sourceHash := fmt.Sprintf("%x", hash.Sum(nil))

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&generated)
	fmt.Fprintln(&generated, "package native")
	fmt.Fprintln(&generated)
	fmt.Fprintf(&generated, "const macroContractSourceSHA256 = %q\n\n", sourceHash)
	fmt.Fprintln(&generated, "const (")
	for _, row := range profiles {
		fmt.Fprintf(&generated, "\t%s byte = 0x%02X\n", goFeatureProfileName(row.name), row.value)
	}
	fmt.Fprintln(&generated, ")")
	fmt.Fprintln(&generated)
	fmt.Fprintln(&generated, "const (")
	for _, row := range features {
		fmt.Fprintf(&generated, "\tBuildFeature%s byte = 0x%02X\n", row.name, row.value)
	}
	fmt.Fprintln(&generated, ")")
	fmt.Fprintln(&generated)
	fmt.Fprintln(&generated, "var macroActionContracts = map[byte]macroActionContract{")
	for _, row := range actions {
		fmt.Fprintf(
			&generated,
			"\t0x%02X: {captureLength: 0x%02X}, // %s\n",
			row.opcode,
			row.captureLength,
			row.name,
		)
	}
	fmt.Fprintln(&generated, "}")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format generated source: %v\n%s", err, generated.String())
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func parseUint8Enum(source []byte, name string) ([]namedValue, error) {
	for _, match := range enumBlock.FindAllSubmatch(source, -1) {
		if string(match[1]) != name {
			continue
		}
		rows := valueRow.FindAllSubmatch(match[2], -1)
		result := make([]namedValue, 0, len(rows))
		seen := make(map[uint8]string)
		for _, row := range rows {
			entry := string(row[1])
			value, err := parseUint8Expression(string(row[2]))
			if err != nil {
				return nil, fmt.Errorf("%s %s: %w", name, entry, err)
			}
			if previous, exists := seen[value]; exists {
				return nil, fmt.Errorf("%s entries %s and %s share 0x%02X", name, previous, entry, value)
			}
			seen[value] = entry
			result = append(result, namedValue{name: entry, value: value})
		}
		if len(result) == 0 {
			return nil, fmt.Errorf("enum %s has no explicit rows", name)
		}
		return result, nil
	}
	return nil, fmt.Errorf("enum %s was not found", name)
}

func parseUint8Expression(expression string) (uint8, error) {
	expression = strings.TrimSpace(expression)
	if shift := shiftExpr.FindStringSubmatch(expression); shift != nil {
		bit, _ := strconv.ParseUint(shift[1], 10, 8)
		return uint8(1 << bit), nil
	}
	value, err := strconv.ParseUint(strings.TrimSuffix(expression, "U"), 0, 8)
	if err != nil {
		return 0, fmt.Errorf("unsupported uint8 expression %q", expression)
	}
	return uint8(value), nil
}

func goFeatureProfileName(name string) string {
	if strings.HasSuffix(name, "FeatureProfile") {
		return "FeatureProfile" + strings.TrimSuffix(name, "FeatureProfile")
	}
	return "FeatureProfile" + strings.TrimSuffix(name, "Profile")
}

func parseOpcodes(source []byte) (map[string]uint8, error) {
	result := make(map[string]uint8)
	for _, match := range enumRow.FindAllSubmatch(source, -1) {
		value, err := strconv.ParseUint(string(match[2]), 0, 8)
		if err != nil {
			return nil, fmt.Errorf("%s value %q: %w", match[1], match[2], err)
		}
		name := string(match[1])
		if previous, exists := result[name]; exists && previous != uint8(value) {
			return nil, fmt.Errorf("duplicate opcode name %s", name)
		}
		result[name] = uint8(value)
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("no opcode rows found")
	}
	return result, nil
}

func parseActions(source []byte, opcodes map[string]uint8) ([]action, error) {
	var result []action
	seenOpcode := make(map[uint8]string)
	for _, match := range actionRow.FindAllSubmatch(source, -1) {
		name := string(match[1])
		opcode, exists := opcodes[name]
		if !exists {
			return nil, fmt.Errorf("action %s has no canonical opcode", name)
		}
		value, err := strconv.ParseUint(string(match[2]), 0, 8)
		if err != nil {
			return nil, fmt.Errorf("%s capture length %q: %w", name, match[2], err)
		}
		if previous, exists := seenOpcode[opcode]; exists {
			return nil, fmt.Errorf("actions %s and %s share opcode 0x%02X", previous, name, opcode)
		}
		seenOpcode[opcode] = name
		result = append(result, action{name: name, opcode: opcode, captureLength: uint8(value)})
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("no PCCONTROLLER_MACRO_ACTION rows found in %s", strings.TrimSpace(string(source)))
	}
	sort.Slice(result, func(i, j int) bool { return result[i].opcode < result[j].opcode })
	return result, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genmacrocontract: "+format+"\n", args...)
	os.Exit(1)
}
